[Kazuki Okamori] EX5 解答 [python]
TakedaLab/B4Lecture-2021 pull request #40
Opened 2021-05-28 08:22 UTC by KazukiOkamori

# WHAT
5/28 k-means実装

mfccとex04も後ほど提出します
(ex05のほうが手を付けやすかったので...)
# RESULT
![ex05_k_means(data1 csv)](https://user-images.githubusercontent.com/82012079/119953134-a52d9080-bfd8-11eb-9d6f-6f0325639407.png)
![ex05_k_means(data2 csv)](https://user-images.githubusercontent.com/82012079/119953131-a494fa00-bfd8-11eb-97eb-dc996ddb36b3.png)
![ex05_k_means(data3 csv)](https://user-images.githubusercontent.com/82012079/119953126-a3fc6380-bfd8-11eb-9126-37bba5921ce8.png)

# WIP

2021-05-31 07:23 UTC, KazukiOkamori commented
MFCCも実装したのでレビューお願いいたします．

2021-05-31 13:13 UTC, inuzukam commented
## 課題について
### k-means
クラスタリングについて，分割の色分けがおかしいようです．
例えばはじめの図の左上と右上の重心の間の垂直二等分線を考えると，左上の重心の方が近い点群も青色に塗られているように見えます．
2つ目の図についても同様です．
また，どのデータを何分割したかをタイトルに付けるとより見やすくなると思います．

### MFCC
フィルタバンクの作成からMFCCの図示までよくできていると思います！
可能であればフィルバンクの図示もあるといいですね．

コードの内容についてはまた確認しますのでもうしばらくお待ち下さい．

2021-06-01 04:00 UTC, inuzukam commented
k-meansに関してですが，初期値によらず，重心を求める処理が一度しか行われていないようです．

2021-06-01 04:39 UTC, inuzukam requested changes
## コードについて
k-meansのがうまくできていないようなので，特に`divide_cluster`の部分を確認してみてください．
mfcc部分の処理に関しては問題なくできていると思います．

2021-06-01 04:39 UTC, inuzukam commented on ex05/k_okamori/ex05_k_means_okamori.py
> +            is_changed = not np.array_equal(self.default, default_previous)
原因をまだ特定できていませんが，この部分の処理で最短距離の重心の判定がうまくできておらず，処理が1回しか行われていない可能性があります．

2021-06-01 08:46 UTC, KazukiOkamori commented on ex05/k_okamori/ex05_k_means_okamori.py
> +            is_changed = not np.array_equal(self.default, default_previous)
ここは原因がわかりました

            default_previous = self.default  # 前回の重心を記録

この部分で参照渡しが行われていたため
self.default の更新と同時に default_previous も更新されてしまい，
is_changed が False になってしまっていたのが原因でした．
なので

            default_previous = np.copy(self.default)  # 前回の重心を記録

というふうに直しました．

他のところも直して更新します．

2021-06-01 14:24 UTC, KazukiOkamori commented
修正終わりました！

2021-06-02 11:00 UTC, inuzukam approved these changes
k-meansの結果も正しく出るようになって良いと思います！
お疲れさまでした！

2021-06-02 11:00 UTC, merged