[Sehun Kim] EX○ 解答 [matlab or python]
TakedaLab/B4Lecture-2021 pull request #5
Opened 2021-04-23 05:35 UTC by KimSehun725

# WHAT

# RESULT

# WIP

2021-04-26 07:02 UTC, Secondtonumb commented on ex1/sehunkim/ex01_Kim.py
> +#sampling rate = 44100Hz
Use [argparse](https://docs.python.org/ja/3/library/argparse.html) then you can set parameters while running the code rathen than changing variables everytime.
This is very important when you are writing huge code.

2021-04-26 07:07 UTC, Secondtonumb commented on ex1/sehunkim/ex01_Kim.py
> +    for frame_no in range (n_of_frame) :
too much space

2021-04-26 08:46 UTC, Secondtonumb commented on ex1/sehunkim/ex01_Kim.py
> +    return result
Frame shift should also be done here.
```
result[start: start+win_frame] = ...
start += win_frame -overlap
result[start: start+win_frame] = ...
```

2021-04-26 08:47 UTC, Secondtonumb commented on ex1/sehunkim/ex01_Kim.py
> +
with`plt.ylim` you can set limitation for each axis and align subplot up.

2021-04-26 08:53 UTC, Secondtonumb requested changes
It's a nice way to pad the whole `wav_array ` before windowing.Good Job.
And I can tell that you've almostly under how stft/istft works and most of the part is correct(Such as you kept y-axis label in linear style except of changing them into 'log' which is wrong), just slightly debug and code format changing is needed.
頑張ってください！

2021-04-27 01:09 UTC, Secondtonumb reviewed
Add you new synthesized plot and I'll approve it!

2021-04-27 07:30 UTC, yoshikawa-tatsuya approved these changes
よく書けていると思います。argparseを使えるとなお良いと思います。

2021-04-28 05:09 UTC, merged