[Kajiwara Daishin] ex6 解答 [python]
TakedaLab/B4Lecture-2021 pull request #50
Opened 2021-06-04 12:12 UTC by shin04

詳細なコメントが書けてないですが一旦pr出します
よろしくお願いします🙇‍♂️

# WHAT
data1-3に対して主成分分析を実行

# RESULT
実行コマンド
```
$ python main.py -rs result
```

![data1](https://user-images.githubusercontent.com/11458641/120799118-438d9900-c579-11eb-83be-6795847e8226.png)
![data2,png](https://user-images.githubusercontent.com/11458641/120799122-44bec600-c579-11eb-8910-4776358e2795.png)
![data2_transformed](https://user-images.githubusercontent.com/11458641/120799120-44262f80-c579-11eb-8ad2-fd73df499c14.png)

# WIP
- コメント書く
- リファクタ
- gitが荒れててすいません

2021-06-04 12:30 UTC, shin04 commented
コメント追加しました

2021-06-07 04:09 UTC, inuzukam requested changes
## 課題について
寄与率の計算や固有ベクトル図示，二次元平面への射影までうまく計算できていると思います！
data3.csvに関しては寄与率90%以上に何次元必要かの解答もお願いします．
また，余力があれば標準化を行った場合の結果も見てみてください．
https://qiita.com/koshian2/items/2e69cb4981ae8fbd3bda

## コードについて
コメントや関数のドキュメントまでよく書けていると思います！
気になった点についていくつかコメントしたので確認お願いします．

2021-06-07 04:09 UTC, inuzukam commented on ex_6/kajiwara/main.py
> +    print("pca3 contribution rate:", pca3.contribution_rate)
寄与率のリストを表示するのではなく，今回の課題の寄与率90%以上にするためには何次元必要化を表示できるようにすると良いと思います．

2021-06-07 04:09 UTC, inuzukam commented on ex_6/kajiwara/pca.py
> +
f文字列を用いたほうがスッキリ書けます．
https://note.nkmk.me/python-f-strings/
```
        assert X.shape[1] == 1, f'The dimensions are different, expected {X.shape[1]}, but {self.dim} given'
```

2021-06-08 02:01 UTC, shin04 commented on ex_6/kajiwara/main.py
> +    args = parser.parse_args()
62d05ee6b6467ddd4596d1c18c9531c316f89a0d で修正しました

2021-06-08 02:02 UTC, shin04 commented on ex_6/kajiwara/main.py
> +                print(err)
f781fec38eae291bc05cb6100cbc42a5c9c32019 で修正しました

2021-06-08 02:02 UTC, shin04 commented on ex_6/kajiwara/main.py
> +    print("pca3 contribution rate:", pca3.contribution_rate)
f781fec38eae291bc05cb6100cbc42a5c9c32019 で修正しました

2021-06-08 06:32 UTC, inuzukam approved these changes
修正確認しました．お疲れさまでした！
Conflictは発生しているのでMergeは後ほど行います．

2021-06-08 06:53 UTC, merged

2021-06-08 08:19 UTC, shin04 commented
conflictのありがとうございます！